In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
print(__version__)

5.14.1

In [3]:
import cufflinks as cf

In [5]:
init_notebook_mode(connected=True)

In [6]:
cf.go_offline()

In [7]:
df = pd.DataFrame(np.random.randn(1000,4), columns='A B C D'.split())
df

            A         B         C         D
0    0.293705 -0.975547 -1.292249 -0.991307
1    0.500292 -0.960228  1.642420  0.797359
2   -0.628217  1.036317  1.592974 -0.757656
3    0.178602 -0.380412  0.147771  0.853454
4    0.386160  0.080925  0.037826  0.632205
..        ...       ...       ...       ...
995 -0.350582 -0.934308 -0.912367  0.374742
996  1.045627 -0.796636 -1.177196 -1.206322
997 -0.129573 -0.054539  1.915581 -0.775917
998 -0.612202  0.618096 -0.376618  0.877376
999  0.660201  0.674897 -0.570318 -0.928801

[1000 rows x 4 columns]

In [8]:
df.head()

          A         B         C         D
0  0.293705 -0.975547 -1.292249 -0.991307
1  0.500292 -0.960228  1.642420  0.797359
2 -0.628217  1.036317  1.592974 -0.757656
3  0.178602 -0.380412  0.147771  0.853454
4  0.386160  0.080925  0.037826  0.632205

In [9]:
df2 = pd.DataFrame({'Category':['A','B','C'], 'Values':[32,43,50]})
df2

  Category  Values
0        A      32
1        B      43
2        C      50

In [11]:
df.iplot(kind='scatter', x='A', y='B', mode='markers', size=5)

In [13]:
 df2.iplot(kind='bar', x='Category', y='Values')

In [14]:
df.count().iplot(kind='bar')

In [15]:
df.iplot(kind='box')

In [16]:
df3 = pd.DataFrame({'X':[1,2,3,4,5], 'y':[10,20,30,10,20], 'z':[5,4,3,5,6]})
df3

   X   y  z
0  1  10  5
1  2  20  4
2  3  30  3
3  4  10  5
4  5  20  6

In [18]:
df3.iplot(kind='surface')

In [19]:
df3.iplot(kind='surface', colorscale='rdylbu')

In [20]:
df[['A', 'B']].iplot(kind='spread')

c:\python\python391\lib\site-packages\cufflinks\plotlytools.py:849: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.

c:\python\python391\lib\site-packages\cufflinks\plotlytools.py:850: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.

In [21]:
df['A'].iplot(kind='hist')

In [25]:
df['A'].iplot(kind='hist', bins=25)

In [26]:
df.iplot(kind='bubble', x='A', y='B', size='C')

In [27]:
df.scatter_matrix()